# Site settings
title: mitcho (Michael 芳貴 Erlewine)
email: mitcho@mitcho.com
description: > # this means to ignore newlines until "baseurl:"
  I am a linguist broadly interested in the structure of sentences (syntax) and how these structures map to meaning (semantics). I am currently a postdoctoral fellow at the Department of Linguistics at McGill University. In a previous life, I was an active coder in the Mozilla (Firefox) and WordPress open-source communities.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mitcho.com" # the base hostname & protocol for your site

# Build settings
markdown:    kramdown
highlighter: pygments
exclude:     ["_hidden"]
timezone:    America/New_York
gems:
  - jekyll-redirect-from
  - jemoji

disqusid: "http://mitcho.com"

# Permalinks
permalink: /blog/:title/
relative_permalinks: true

# Markdown
kramdown:
  input: GFM # github-flavored markdown

# SASS
sass:
    style: :compressed